<?php
/**
 * ClientTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ORY Hydra
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ClientTest Class Doc Comment
 *
 * @category    Class
 * @description Client
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ClientTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Client"
     */
    public function testClient()
    {
    }

    /**
     * Test attribute "allowed_cors_origins"
     */
    public function testPropertyAllowedCorsOrigins()
    {
    }

    /**
     * Test attribute "audience"
     */
    public function testPropertyAudience()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "client_name"
     */
    public function testPropertyClientName()
    {
    }

    /**
     * Test attribute "client_secret"
     */
    public function testPropertyClientSecret()
    {
    }

    /**
     * Test attribute "client_secret_expires_at"
     */
    public function testPropertyClientSecretExpiresAt()
    {
    }

    /**
     * Test attribute "client_uri"
     */
    public function testPropertyClientUri()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "grant_types"
     */
    public function testPropertyGrantTypes()
    {
    }

    /**
     * Test attribute "jwks"
     */
    public function testPropertyJwks()
    {
    }

    /**
     * Test attribute "jwks_uri"
     */
    public function testPropertyJwksUri()
    {
    }

    /**
     * Test attribute "logo_uri"
     */
    public function testPropertyLogoUri()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "policy_uri"
     */
    public function testPropertyPolicyUri()
    {
    }

    /**
     * Test attribute "redirect_uris"
     */
    public function testPropertyRedirectUris()
    {
    }

    /**
     * Test attribute "request_object_signing_alg"
     */
    public function testPropertyRequestObjectSigningAlg()
    {
    }

    /**
     * Test attribute "request_uris"
     */
    public function testPropertyRequestUris()
    {
    }

    /**
     * Test attribute "response_types"
     */
    public function testPropertyResponseTypes()
    {
    }

    /**
     * Test attribute "scope"
     */
    public function testPropertyScope()
    {
    }

    /**
     * Test attribute "sector_identifier_uri"
     */
    public function testPropertySectorIdentifierUri()
    {
    }

    /**
     * Test attribute "subject_type"
     */
    public function testPropertySubjectType()
    {
    }

    /**
     * Test attribute "token_endpoint_auth_method"
     */
    public function testPropertyTokenEndpointAuthMethod()
    {
    }

    /**
     * Test attribute "tos_uri"
     */
    public function testPropertyTosUri()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "userinfo_signed_response_alg"
     */
    public function testPropertyUserinfoSignedResponseAlg()
    {
    }
}
