<?php
/**
 * ConsentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ORY Hydra
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ConsentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ConsentRequest
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConsentRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConsentRequest"
     */
    public function testConsentRequest()
    {
    }

    /**
     * Test attribute "acr"
     */
    public function testPropertyAcr()
    {
    }

    /**
     * Test attribute "challenge"
     */
    public function testPropertyChallenge()
    {
    }

    /**
     * Test attribute "client"
     */
    public function testPropertyClient()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "login_challenge"
     */
    public function testPropertyLoginChallenge()
    {
    }

    /**
     * Test attribute "login_session_id"
     */
    public function testPropertyLoginSessionId()
    {
    }

    /**
     * Test attribute "oidc_context"
     */
    public function testPropertyOidcContext()
    {
    }

    /**
     * Test attribute "request_url"
     */
    public function testPropertyRequestUrl()
    {
    }

    /**
     * Test attribute "requested_access_token_audience"
     */
    public function testPropertyRequestedAccessTokenAudience()
    {
    }

    /**
     * Test attribute "requested_scope"
     */
    public function testPropertyRequestedScope()
    {
    }

    /**
     * Test attribute "skip"
     */
    public function testPropertySkip()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }
}
