<?php
/**
 * HandledConsentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ORY Hydra
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * HandledConsentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description HandledConsentRequest
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class HandledConsentRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HandledConsentRequest"
     */
    public function testHandledConsentRequest()
    {
    }

    /**
     * Test attribute "grant_access_token_audience"
     */
    public function testPropertyGrantAccessTokenAudience()
    {
    }

    /**
     * Test attribute "grant_scope"
     */
    public function testPropertyGrantScope()
    {
    }

    /**
     * Test attribute "remember"
     */
    public function testPropertyRemember()
    {
    }

    /**
     * Test attribute "remember_for"
     */
    public function testPropertyRememberFor()
    {
    }

    /**
     * Test attribute "session"
     */
    public function testPropertySession()
    {
    }
}
