<?php
/**
 * OpenIDConnectContextTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ORY Hydra
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * OpenIDConnectContextTest Class Doc Comment
 *
 * @category    Class
 * @description OpenIDConnectContext
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OpenIDConnectContextTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OpenIDConnectContext"
     */
    public function testOpenIDConnectContext()
    {
    }

    /**
     * Test attribute "acr_values"
     */
    public function testPropertyAcrValues()
    {
    }

    /**
     * Test attribute "display"
     */
    public function testPropertyDisplay()
    {
    }

    /**
     * Test attribute "id_token_hint_claims"
     */
    public function testPropertyIdTokenHintClaims()
    {
    }

    /**
     * Test attribute "login_hint"
     */
    public function testPropertyLoginHint()
    {
    }

    /**
     * Test attribute "ui_locales"
     */
    public function testPropertyUiLocales()
    {
    }
}
