<?php
/**
 * WellKnownTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ORY Hydra
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * WellKnownTest Class Doc Comment
 *
 * @category    Class
 * @description It includes links to several endpoints (e.g. /oauth2/token) and exposes information on supported signature algorithms among others.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WellKnownTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WellKnown"
     */
    public function testWellKnown()
    {
    }

    /**
     * Test attribute "authorization_endpoint"
     */
    public function testPropertyAuthorizationEndpoint()
    {
    }

    /**
     * Test attribute "backchannel_logout_session_supported"
     */
    public function testPropertyBackchannelLogoutSessionSupported()
    {
    }

    /**
     * Test attribute "backchannel_logout_supported"
     */
    public function testPropertyBackchannelLogoutSupported()
    {
    }

    /**
     * Test attribute "claims_parameter_supported"
     */
    public function testPropertyClaimsParameterSupported()
    {
    }

    /**
     * Test attribute "claims_supported"
     */
    public function testPropertyClaimsSupported()
    {
    }

    /**
     * Test attribute "end_session_endpoint"
     */
    public function testPropertyEndSessionEndpoint()
    {
    }

    /**
     * Test attribute "frontchannel_logout_session_supported"
     */
    public function testPropertyFrontchannelLogoutSessionSupported()
    {
    }

    /**
     * Test attribute "frontchannel_logout_supported"
     */
    public function testPropertyFrontchannelLogoutSupported()
    {
    }

    /**
     * Test attribute "grant_types_supported"
     */
    public function testPropertyGrantTypesSupported()
    {
    }

    /**
     * Test attribute "id_token_signing_alg_values_supported"
     */
    public function testPropertyIdTokenSigningAlgValuesSupported()
    {
    }

    /**
     * Test attribute "issuer"
     */
    public function testPropertyIssuer()
    {
    }

    /**
     * Test attribute "jwks_uri"
     */
    public function testPropertyJwksUri()
    {
    }

    /**
     * Test attribute "registration_endpoint"
     */
    public function testPropertyRegistrationEndpoint()
    {
    }

    /**
     * Test attribute "request_parameter_supported"
     */
    public function testPropertyRequestParameterSupported()
    {
    }

    /**
     * Test attribute "request_uri_parameter_supported"
     */
    public function testPropertyRequestUriParameterSupported()
    {
    }

    /**
     * Test attribute "require_request_uri_registration"
     */
    public function testPropertyRequireRequestUriRegistration()
    {
    }

    /**
     * Test attribute "response_modes_supported"
     */
    public function testPropertyResponseModesSupported()
    {
    }

    /**
     * Test attribute "response_types_supported"
     */
    public function testPropertyResponseTypesSupported()
    {
    }

    /**
     * Test attribute "revocation_endpoint"
     */
    public function testPropertyRevocationEndpoint()
    {
    }

    /**
     * Test attribute "scopes_supported"
     */
    public function testPropertyScopesSupported()
    {
    }

    /**
     * Test attribute "subject_types_supported"
     */
    public function testPropertySubjectTypesSupported()
    {
    }

    /**
     * Test attribute "token_endpoint"
     */
    public function testPropertyTokenEndpoint()
    {
    }

    /**
     * Test attribute "token_endpoint_auth_methods_supported"
     */
    public function testPropertyTokenEndpointAuthMethodsSupported()
    {
    }

    /**
     * Test attribute "userinfo_endpoint"
     */
    public function testPropertyUserinfoEndpoint()
    {
    }

    /**
     * Test attribute "userinfo_signing_alg_values_supported"
     */
    public function testPropertyUserinfoSigningAlgValuesSupported()
    {
    }
}
