<?php
/**
 * AdminApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ORY Hydra
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdminApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdminApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for acceptConsentRequest
     *
     * Accept an consent request.
     *
     */
    public function testAcceptConsentRequest()
    {
    }

    /**
     * Test case for acceptLoginRequest
     *
     * Accept an login request.
     *
     */
    public function testAcceptLoginRequest()
    {
    }

    /**
     * Test case for acceptLogoutRequest
     *
     * Accept a logout request.
     *
     */
    public function testAcceptLogoutRequest()
    {
    }

    /**
     * Test case for createJsonWebKeySet
     *
     * Generate a new JSON Web Key.
     *
     */
    public function testCreateJsonWebKeySet()
    {
    }

    /**
     * Test case for createOAuth2Client
     *
     * Create an OAuth 2.0 client.
     *
     */
    public function testCreateOAuth2Client()
    {
    }

    /**
     * Test case for deleteJsonWebKey
     *
     * Delete a JSON Web Key.
     *
     */
    public function testDeleteJsonWebKey()
    {
    }

    /**
     * Test case for deleteJsonWebKeySet
     *
     * Delete a JSON Web Key Set.
     *
     */
    public function testDeleteJsonWebKeySet()
    {
    }

    /**
     * Test case for deleteOAuth2Client
     *
     * Deletes an OAuth 2.0 Client.
     *
     */
    public function testDeleteOAuth2Client()
    {
    }

    /**
     * Test case for flushInactiveOAuth2Tokens
     *
     * Flush Expired OAuth2 Access Tokens.
     *
     */
    public function testFlushInactiveOAuth2Tokens()
    {
    }

    /**
     * Test case for getConsentRequest
     *
     * Get consent request information.
     *
     */
    public function testGetConsentRequest()
    {
    }

    /**
     * Test case for getJsonWebKey
     *
     * Fetch a JSON Web Key.
     *
     */
    public function testGetJsonWebKey()
    {
    }

    /**
     * Test case for getJsonWebKeySet
     *
     * Retrieve a JSON Web Key Set.
     *
     */
    public function testGetJsonWebKeySet()
    {
    }

    /**
     * Test case for getLoginRequest
     *
     * Get an login request.
     *
     */
    public function testGetLoginRequest()
    {
    }

    /**
     * Test case for getLogoutRequest
     *
     * Get a logout request.
     *
     */
    public function testGetLogoutRequest()
    {
    }

    /**
     * Test case for getOAuth2Client
     *
     * Get an OAuth 2.0 Client..
     *
     */
    public function testGetOAuth2Client()
    {
    }

    /**
     * Test case for introspectOAuth2Token
     *
     * Introspect OAuth2 tokens.
     *
     */
    public function testIntrospectOAuth2Token()
    {
    }

    /**
     * Test case for listOAuth2Clients
     *
     * List OAuth 2.0 Clients.
     *
     */
    public function testListOAuth2Clients()
    {
    }

    /**
     * Test case for listSubjectConsentSessions
     *
     * Lists all consent sessions of a subject.
     *
     */
    public function testListSubjectConsentSessions()
    {
    }

    /**
     * Test case for rejectConsentRequest
     *
     * Reject an consent request.
     *
     */
    public function testRejectConsentRequest()
    {
    }

    /**
     * Test case for rejectLoginRequest
     *
     * Reject a login request.
     *
     */
    public function testRejectLoginRequest()
    {
    }

    /**
     * Test case for rejectLogoutRequest
     *
     * Reject a logout request.
     *
     */
    public function testRejectLogoutRequest()
    {
    }

    /**
     * Test case for revokeAuthenticationSession
     *
     * Invalidates all login sessions of a certain user Invalidates a subject's authentication session.
     *
     */
    public function testRevokeAuthenticationSession()
    {
    }

    /**
     * Test case for revokeConsentSessions
     *
     * Revokes consent sessions of a subject for a specific OAuth 2.0 Client.
     *
     */
    public function testRevokeConsentSessions()
    {
    }

    /**
     * Test case for updateJsonWebKey
     *
     * Update a JSON Web Key.
     *
     */
    public function testUpdateJsonWebKey()
    {
    }

    /**
     * Test case for updateJsonWebKeySet
     *
     * Update a JSON Web Key Set.
     *
     */
    public function testUpdateJsonWebKeySet()
    {
    }

    /**
     * Test case for updateOAuth2Client
     *
     * Update an OAuth 2.0 Client.
     *
     */
    public function testUpdateOAuth2Client()
    {
    }
}
