<?php
/**
 * PublicApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ORY Hydra
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PublicApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PublicApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for disconnectUser
     *
     * OpenID Connect Front-Backchannel enabled Logout.
     *
     */
    public function testDisconnectUser()
    {
    }

    /**
     * Test case for discoverOpenIDConfiguration
     *
     * OpenID Connect Discovery.
     *
     */
    public function testDiscoverOpenIDConfiguration()
    {
    }

    /**
     * Test case for oauth2Token
     *
     * The OAuth 2.0 token endpoint.
     *
     */
    public function testOauth2Token()
    {
    }

    /**
     * Test case for oauthAuth
     *
     * The OAuth 2.0 authorize endpoint.
     *
     */
    public function testOauthAuth()
    {
    }

    /**
     * Test case for revokeOAuth2Token
     *
     * Revoke OAuth2 tokens.
     *
     */
    public function testRevokeOAuth2Token()
    {
    }

    /**
     * Test case for userinfo
     *
     * OpenID Connect Userinfo.
     *
     */
    public function testUserinfo()
    {
    }

    /**
     * Test case for wellKnown
     *
     * JSON Web Keys Discovery.
     *
     */
    public function testWellKnown()
    {
    }
}
